version: '3'
services:
    docker:
        image: docker:dind
        privileged: true
        environment:
            - DOCKER_TLS_CERTDIR=/certs
        volumes:
            - docker-certs:/certs/client
            - data:/var/jenkins_home
        ports:
            - "2376:2376"
    blueocean:
        image: jenkinsci/blueocean
        environment:
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        volumes:
            - data:/var/jenkins_home
            - docker-certs:/certs/client:ro
        ports:
            - "8080:8080"
            - "50000:50000"
        depends_on:
            - docker
volumes:
    docker-certs: 
    data: 
